# Generated by Django 4.0.2 on 2022-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
