# Generated by Django 4.0.2 on 2022-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='anonymous',
        ),
    ]
